"""
玩家域共享常量与稳定错误码

错误码必须稳定（DOC-PLAYER-007 RULE-PLAYER-035）：拒绝是可测试的契约，
Client 与日志只见到安全 reason code，不见内部细节。
"""

# DOC-PLAYER-001 §8：相同幂等 key 不同 payload
DENY_IDEMPOTENCY_PAYLOAD_CONFLICT = "PLAYER_IDEMPOTENCY_PAYLOAD_CONFLICT"

# DOC-PLAYER-002 §8：同序号不同 payload
DENY_INPUT_SEQUENCE_CONFLICT = "PLAYER_INPUT_SEQUENCE_CONFLICT"

# DOC-PLAYER-003 §7.1 禁止转换表
DENY_MODE_BLOCKED_COMBAT = "PLAYER_MODE_BLOCKED_COMBAT"
DENY_MODE_BLOCKED_RESIDENT_STATE = "PLAYER_MODE_BLOCKED_RESIDENT_STATE"
DENY_MODE_BLOCKED_SYSTEM = "PLAYER_MODE_BLOCKED_SYSTEM"
DENY_MAYOR_AUTHORITY_REVOKED = "PLAYER_MAYOR_AUTHORITY_REVOKED"

# DOC-PLAYER-004 §8
DENY_COMMAND_ID_CONFLICT = "PLAYER_COMMAND_ID_CONFLICT"
DENY_CAPABILITY_STALE = "PLAYER_CAPABILITY_STALE"

# DOC-PLAYER-005 §8
DENY_COMPILATION_STALE = "PLAYER_COMPILATION_STALE"

#: DOC-PLAYER-002 §5：移动 intent 采样窗口上限（毫秒）
MAX_SAMPLE_DURATION_MS = 100

#: DOC-PLAYER-002 §9：每玩家移动 intent 限速（每秒）
MOVE_INTENT_RATE_LIMIT_PER_SECOND = 25

#: DOC-PLAYER-004 §5：PlayerCommand payload 上限（字节）
MAX_COMMAND_PAYLOAD_BYTES = 16 * 1024

#: DOC-PLAYER-004 §9：交互候选数量上限
MAX_INTERACTION_CANDIDATES = 16

#: DOC-PLAYER-005 §5：说话文本长度（Unicode scalar）
MIN_SPEECH_TEXT_LENGTH = 1
MAX_SPEECH_TEXT_LENGTH = 1000

#: DOC-PLAYER-005 §5：说话文本显示行数上限
MAX_SPEECH_DISPLAY_LINES = 8

#: DOC-PLAYER-005 §9：每玩家每 10 秒最多解析次数
NL_PARSE_RATE_LIMIT_PER_10S = 5

#: DOC-PLAYER-009 §5.1：确认挑战有效期（毫秒）
ADMIN_CHALLENGE_EXPIRES_IN_MS = 60_000

#: DOC-PLAYER-001 §3：AI 核心居民配额区间（玩家 Resident 不计入）
CORE_AI_RESIDENT_QUOTA_MIN = 8
CORE_AI_RESIDENT_QUOTA_MAX = 12
