"""MAGIC 域：魔法系统（docs/11-magic，DOC-MAGIC-001..012）"""

from .balance import (
    BALANCE_V1,
    DISPLACEMENT_CAPABILITIES,
    ECONOMY_IMPACT_CHANNELS,
    EFFECT_PORT_CALLS,
    BalanceError,
    MagicBalanceConfig,
    MagicSimulationObservation,
    audit_catalog_envelope,
    audit_handler_no_displacement,
    audit_item_envelope,
    audit_magic_corpus,
    check_magic_envelope,
    lint_no_teleport,
)
from .candidates import (
    FALLBACK_ACTION_BLACKLIST,
    CandidateError,
    DailyCastBudget,
    build_candidates,
    check_declared_purpose,
    check_targets_visible,
    fallback_action_allowed,
    make_witness_input,
)
from .casting import (
    CastingEngine,
    CastingError,
    CastVerdict,
    SpellCastCommand,
    SpellCastCommitted,
)
from .constants import (
    ACTIVITY_MULT,
    ALLOWED_MECHANICAL_HOOKS,
    ALLOWED_TRINKET_MODIFIERS,
    ANCHOR_MAX_DURATION_GAME_MINUTES,
    ANCHOR_SCENE_CAP,
    CANDIDATES_CAP,
    CAST_REASON_CODES,
    CHARGES_MAX_MAX,
    CHARGES_MAX_MIN,
    COOLDOWN_MAX_GAME_MINUTES,
    DAILY_INSTANT_CAST_BUDGET,
    EFFECT_MAX_DURATION_GAME_MINUTES,
    EXHAUSTION_ENTER_THRESHOLD,
    EXHAUSTION_EXIT_THRESHOLD,
    HEAL_DAILY_CAP_BPS,
    KNOWLEDGE_ENTRIES_CAP,
    MANA_BASE_REGEN,
    MANA_COST_MAX,
    MANA_COST_MIN,
    MANA_MAX_BASE,
    MANA_MAX_CAP,
    RECHARGE_MANA_PER_CHARGE,
    RECHARGE_MIN_SCHOOL_RATING,
    REGEN_BATCH_CAP,
    REGEN_INCREMENT_MAX,
    SCENE_EFFECT_INSTANCE_CAP,
    STUDY_WORK_UNITS_MIN,
    STUDY_WORK_UNITS_PER_10_MANA,
    TIDE_Q1000_DEFAULT,
    TIDE_Q1000_MAX,
    TIDE_Q1000_MIN,
    TRINKET_TIDE_BONUS_CAP_Q1000,
    ActivityKind,
    CastKind,
    ChargeState,
    DeclaredPurpose,
    EffectInstanceState,
    KnowledgeState,
    LegalOverride,
    Legality,
    MagicItemKind,
    SourceKind,
    TargetMode,
    VerdictClassification,
)
from .cosmology import (
    CosmologyEntry,
    CosmologyError,
    CosmologyRegistry,
    build_default_cosmology,
)
from .effects import (
    EFFECT_IDS,
    EFFECT_PARAM_FIELDS,
    EFFECT_PURPOSE_WHITELIST,
    HARMFUL_EFFECTS,
    RESCUE_EFFECTS,
    EffectContext,
    EffectError,
    EffectInstanceStore,
    HealDailyLedger,
    WorldMagicEffectInstance,
    apply_effect,
    check_effect_preconditions,
    run_effect_bindings,
)
from .items import (
    MagicItemChargeRegistry,
    MagicItemChargeState,
    MagicItemDefinition,
    MagicItemError,
    MagicItemRegistry,
    MagicItemService,
    audit_magic_item_definitions,
    build_default_magic_items,
    compose_trinket_modifiers,
    decode_magic_item_definition,
)
from .learning import (
    KnowledgeEntry,
    LearningError,
    LearningRegistry,
    SpellKnowledge,
)
from .mana import (
    CasterRegistry,
    CasterState,
    ManaError,
    ManaRegenResult,
    compose_tide_q1000,
    mana_max_for,
    regen_increment,
)
from .player import (
    REASON_FEEDBACK_ZH,
    PlayerCastingError,
    PlayerCastingService,
    PlayerCastSpellCommand,
    feedback_coverage_complete,
    feedback_for,
)
from .presentation import (
    FALLBACK_VFX_ID,
    MagicPresentation,
    PresentationError,
    PresentationRegistry,
    audit_presentation_closure,
    build_default_presentations,
    decode_presentation,
    illusion_projection_for_observer,
)
from .schools import (
    SCHOOL_IDS,
    EffectCategory,
    SchoolDefinition,
    SchoolError,
    SchoolRegistry,
    arbitrate_school,
    assert_no_teleport_semantics,
    build_default_schools,
    lint_school_scope,
)
from .spells import (
    SPELL_DEFINITION_FIELDS,
    SpellCatalog,
    SpellDefinition,
    SpellError,
    build_default_spell_catalog,
    decode_spell_definition,
    study_work_units_for,
    validate_target_arguments,
)

__all__ = [name for name in dir() if not name.startswith("_")]
